### ISSUE TITLE
Provide useful error for migrating from `master` -> `main` while upgrading

### ISSUE THREAD

**Issue by jromero** [buildpacks/homebrew-tap#10]
### Summary
If a user has previously tapped `buildpacks/tap` they will no longer get upgrades via `brew upgrade pack` due to the change of default branch from `master` to `main`.

The steps that should be presented to the user should be:
```bash
brew untap buildpacks/tap
brew tap buildpacks/tap
brew upgrade pack
```

### Proposed solution
https://github.com/Homebrew/brew/issues/7746#issuecomment-649582087

**Comment by nebhale** [comment]
Suggested content until we've got a page with more detail:

```
  ohai "Language Matters"

  opoo "The Cloud Native Builpdacks project is updating its language in an"
  opoo "effort to be more inclusive. Part of that effort includes renaming our"
  opoo "default git branches from 'master' to 'main'."
  opoo ""

  odie """To upgrade pack, retap it with:
    brew untap buildpacks/tap
    brew tap buildpacks/tap
    brew upgrade pack"""
```

**Comment by Kampe** [comment]
These instructions only kick the can further down the road:
```
$     brew upgrade pack
Error: Formulae found in multiple taps:
       * buildpack/tap/pack
       * buildpacks/tap/pack

Please use the fully-qualified name (e.g. buildpack/tap/pack) to refer to the formula.
```

**Comment by lukasluecke** [comment]
<img width="717" alt="CleanShot 2020-07-28 at 21 03 38@2x" src="https://user-images.githubusercontent.com/6652670/88710043-4d9f6980-d116-11ea-92df-2d8a96ad2ef5.png">

Not really a useful error, if the name of the tap doesn't match what's used (see the previous comment, originally the formula seems to have been available under `buildpack`) 🙊

**Comment by brandonjbjelland** [comment]
This is frustrating and still broken. I was unable to find any successful sequence of `brew untap`, `brew tap`, and `brew upgrade` with fully qualified taps or not. This effectively breaks brew system-wide.

**Comment by jromero** [comment]
It's my understanding that homebrew changed something recently that makes it so that the added error actually prevents untapping.

This is very much a homebrew limitation (changing branches).

Here are a few steps to manually update the branch:

```shell
cd​ /usr/local/Homebrew/Library/Taps/buildpacks/homebrew-tap
git fetch origin
git checkout main
git remote set-head origin main
```

Give that a try.

**Comment by dannyxu2015** [comment]
> It's my understanding that homebrew changed something recently that makes it so that the added error actually prevents untapping.
> 
> This is very much a homebrew limitation (changing branches).
> 
> Here are a few steps to manually update the branch:
> 
> ```shell
> cd​ /usr/local/Homebrew/Library/Taps/buildpacks/homebrew-tap
> git fetch origin
> git checkout main
> git remote set-head origin main
> ```
> 
> Give that a try.

save my live, thanks!
