### ISSUE TITLE
Add pack to the offical homebrew repo

### ISSUE THREAD

**Issue by zmackie** [buildpacks/homebrew-tap#6]
@ameyer-pivotal Any idea what we'd need to do for this?

**Comment by jromero** [comment]
FWIW: One of the downsides of the official homebrew repo is that we would need to post a PR and await approval vs managing it ourselves via this repo.

**Comment by ameyer-pivotal** [comment]
I had considered that downside too. I personally don't think having an "official" tap is worth the maintenance effort. I'd say that as a homebrew user, I'm perfectly accustomed to using third-party taps.

Should we close this?

**Comment by jromero** [comment]
Given that there's a short form of install the step, `brew install buildpacks/tap/pack`, I don't see much value going with "official" repo all things considered.

@zmackie feel free to reopen if you'd like to continue discussing it.

**Comment by zmackie** [comment]
For me the big upside was getting install stats. But maybe we can get those
with a tap?

**Comment by jromero** [comment]
Stats are already available from what I can tell:

https://formulae.brew.sh/analytics/install/30d/:
![image](https://user-images.githubusercontent.com/475559/75790032-35c2e580-5d30-11ea-843c-d68c7c30841e.png)
![image](https://user-images.githubusercontent.com/475559/75790134-5a1ec200-5d30-11ea-9d67-3c8cca2546fa.png)

**Comment by zmackie** [comment]
Well there you go!
